// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TestHosts.IntegrationTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Agency Banking Transactions")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("base")]
    [global::NUnit.Framework.CategoryAttribute("system")]
    [global::NUnit.Framework.CategoryAttribute("glaccount")]
    [global::NUnit.Framework.CategoryAttribute("float")]
    [global::NUnit.Framework.CategoryAttribute("settlement")]
    [global::NUnit.Framework.CategoryAttribute("agent")]
    [global::NUnit.Framework.CategoryAttribute("customer")]
    [global::NUnit.Framework.CategoryAttribute("transactions")]
    public partial class AgencyBankingTransactionsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "system",
                "glaccount",
                "float",
                "settlement",
                "agent",
                "customer",
                "transactions"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "Agency Banking Transactions", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AgencyBankingFeature.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
#line 5
    await testRunner.GivenAsync("the Agency Banking API is available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "institutionCode",
                        "BANK001"});
            table1.AddRow(new string[] {
                        "institutionName",
                        "Enterprise Bank"});
            table1.AddRow(new string[] {
                        "defaultCurrency",
                        "KES"});
            table1.AddRow(new string[] {
                        "timezone",
                        "Africa/Nairobi"});
            table1.AddRow(new string[] {
                        "settlementMode",
                        "NET"});
#line 7
 await testRunner.WhenAsync("I initialize the system with:", ((string)(null)), table1, "When ");
#line hidden
            global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "code",
                        "200100"});
            table2.AddRow(new string[] {
                        "name",
                        "Agent Float GL"});
            table2.AddRow(new string[] {
                        "type",
                        "LIABILITY"});
            table2.AddRow(new string[] {
                        "currency",
                        "KES"});
#line 15
    await testRunner.WhenAsync("I create a GL account with:", ((string)(null)), table2, "When ");
#line hidden
            global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "code",
                        "200200"});
            table3.AddRow(new string[] {
                        "name",
                        "Settlement Suspense GL"});
            table3.AddRow(new string[] {
                        "type",
                        "LIABILITY"});
            table3.AddRow(new string[] {
                        "currency",
                        "KES"});
#line 22
await testRunner.WhenAsync("I create a GL account with:", ((string)(null)), table3, "When ");
#line hidden
            global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "code",
                        "400100"});
            table4.AddRow(new string[] {
                        "name",
                        "Agent Commission GL"});
            table4.AddRow(new string[] {
                        "type",
                        "EXPENSE"});
            table4.AddRow(new string[] {
                        "currency",
                        "KES"});
#line 29
        await testRunner.WhenAsync("I create a GL account with:", ((string)(null)), table4, "When ");
#line hidden
            global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "code",
                        "200300"});
            table5.AddRow(new string[] {
                        "name",
                        "Reversal GL"});
            table5.AddRow(new string[] {
                        "type",
                        "LIABILITY"});
            table5.AddRow(new string[] {
                        "currency",
                        "KES"});
#line 36
 await testRunner.WhenAsync("I create a GL account with:", ((string)(null)), table5, "When ");
#line hidden
            global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "code",
                        "400200"});
            table6.AddRow(new string[] {
                        "name",
                        "Fee Income GL"});
            table6.AddRow(new string[] {
                        "type",
                        "INCOME"});
            table6.AddRow(new string[] {
                        "currency",
                        "KES"});
#line 43
 await testRunner.WhenAsync("I create a GL account with:", ((string)(null)), table6, "When ");
#line hidden
            global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "accountNumber",
                        "999000001"});
            table7.AddRow(new string[] {
                        "bankCode",
                        "001"});
            table7.AddRow(new string[] {
                        "currency",
                        "KES"});
            table7.AddRow(new string[] {
                        "accountName",
                        "Main Settlement Account"});
#line 50
    await testRunner.WhenAsync("I create a settlement account with:", ((string)(null)), table7, "When ");
#line hidden
            global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "agentId",
                        "SAG001"});
            table8.AddRow(new string[] {
                        "name",
                        "Staging Estate"});
            table8.AddRow(new string[] {
                        "phoneNumber",
                        "254700000001"});
            table8.AddRow(new string[] {
                        "email",
                        "superagent@bank.com"});
            table8.AddRow(new string[] {
                        "region",
                        "NAIROBI"});
            table8.AddRow(new string[] {
                        "dailyLimit",
                        "10000000"});
            table8.AddRow(new string[] {
                        "minimumFloat",
                        "500000"});
#line 57
     await testRunner.WhenAsync("I create a super agent with:", ((string)(null)), table8, "When ");
#line hidden
            global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "agentId",
                        "AGT001"});
            table9.AddRow(new string[] {
                        "superAgentId",
                        "SAG001"});
            table9.AddRow(new string[] {
                        "name",
                        "Staging Merchant 1"});
            table9.AddRow(new string[] {
                        "phoneNumber",
                        "254700000010"});
            table9.AddRow(new string[] {
                        "email",
                        "agent@bank.com"});
            table9.AddRow(new string[] {
                        "location",
                        "NAIROBI CBD"});
            table9.AddRow(new string[] {
                        "dailyLimit",
                        "100000"});
            table9.AddRow(new string[] {
                        "minimumFloat",
                        "10000"});
#line 67
     await testRunner.WhenAsync("I create a retail agent with:", ((string)(null)), table9, "When ");
#line hidden
            global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "activatedBy",
                        "SYSTEM_ADMIN"});
#line 78
    await testRunner.WhenAsync("I activate agent \"AGT001\" with:", ((string)(null)), table10, "When ");
#line hidden
            global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "minimumFloat",
                        "10000"});
            table11.AddRow(new string[] {
                        "maximumFloat",
                        "500000"});
            table11.AddRow(new string[] {
                        "dailyFloatLimit",
                        "1000000"});
#line 82
    await testRunner.WhenAsync("I configure float for agent \"AGT001\" with:", ((string)(null)), table11, "When ");
#line hidden
            global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "transactionId",
                        "FLT000001"});
            table12.AddRow(new string[] {
                        "amount",
                        "10000"});
            table12.AddRow(new string[] {
                        "sourceAccount",
                        "TREASURY_GL"});
            table12.AddRow(new string[] {
                        "narration",
                        "Initial float funding"});
#line 88
    await testRunner.WhenAsync("I credit float to agent \"AGT001\" with:", ((string)(null)), table12, "When ");
#line hidden
            global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table13.AddRow(new string[] {
                        "customerId",
                        "CUST001"});
            table13.AddRow(new string[] {
                        "fullName",
                        "John Doe"});
            table13.AddRow(new string[] {
                        "phoneNumber",
                        "254711111111"});
            table13.AddRow(new string[] {
                        "nationalId",
                        "12345678"});
            table13.AddRow(new string[] {
                        "accountNumber",
                        "100200300"});
#line 95
    await testRunner.WhenAsync("I create a customer with:", ((string)(null)), table13, "When ");
#line hidden
            global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "approvedBy",
                        "HEAD_OPERATIONS"});
            table14.AddRow(new string[] {
                        "environment",
                        "UAT"});
#line 103
    await testRunner.WhenAsync("I approve go live with:", ((string)(null)), table14, "When ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("AgencyBankingFeature.feature.ndjson", 9);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Successful cash deposit transaction")]
        [global::NUnit.Framework.CategoryAttribute("Deposit")]
        public async global::System.Threading.Tasks.Task SuccessfulCashDepositTransaction()
        {
            string[] tagsOfScenario = new string[] {
                    "Deposit"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful cash deposit transaction", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 109
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table15.AddRow(new string[] {
                            "transactionId",
                            "DEP000001"});
                table15.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table15.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table15.AddRow(new string[] {
                            "amount",
                            "5000"});
                table15.AddRow(new string[] {
                            "currency",
                            "KES"});
                table15.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table15.AddRow(new string[] {
                            "narration",
                            "Cash deposit via agent"});
                table15.AddRow(new string[] {
                            "referenceNumber",
                            "REFDEP001"});
#line 111
    await testRunner.WhenAsync("agent \"AGT001\" performs a cash deposit with:", ((string)(null)), table15, "When ");
#line hidden
#line 121
    await testRunner.ThenAsync("the transaction id \"DEP000001\" should be successful and the transaction status sh" +
                        "ould be \"COMPLETED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 122
    await testRunner.AndAsync("the customer account \"100200300\" balance should be 5000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
    await testRunner.AndAsync("the agent \"AGT001\" float balance should be 5000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Successful cash withdrawal transaction")]
        [global::NUnit.Framework.CategoryAttribute("Withdrawal")]
        public async global::System.Threading.Tasks.Task SuccessfulCashWithdrawalTransaction()
        {
            string[] tagsOfScenario = new string[] {
                    "Withdrawal"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful cash withdrawal transaction", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 126
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table16.AddRow(new string[] {
                            "transactionId",
                            "DEP000001"});
                table16.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table16.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table16.AddRow(new string[] {
                            "amount",
                            "5000"});
                table16.AddRow(new string[] {
                            "currency",
                            "KES"});
                table16.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table16.AddRow(new string[] {
                            "narration",
                            "Cash deposit via agent"});
                table16.AddRow(new string[] {
                            "referenceNumber",
                            "REFDEP001"});
#line 127
    await testRunner.WhenAsync("agent \"AGT001\" performs a cash deposit with:", ((string)(null)), table16, "When ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table17.AddRow(new string[] {
                            "transactionId",
                            "WDL000001"});
                table17.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table17.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table17.AddRow(new string[] {
                            "amount",
                            "2000"});
                table17.AddRow(new string[] {
                            "currency",
                            "KES"});
                table17.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table17.AddRow(new string[] {
                            "narration",
                            "Cash withdrawal via agent"});
                table17.AddRow(new string[] {
                            "referenceNumber",
                            "REFWDL001"});
#line 137
    await testRunner.AndAsync("agent \"AGT001\" performs a cash withdrawal with:", ((string)(null)), table17, "And ");
#line hidden
#line 147
    await testRunner.ThenAsync("the transaction id \"WDL000001\" should be successful and the transaction status sh" +
                        "ould be \"COMPLETED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 148
    await testRunner.AndAsync("the customer account \"100200300\" balance should be 3000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 149
    await testRunner.AndAsync("the agent \"AGT001\" float balance should be 7000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Successful customer balance enquiry")]
        [global::NUnit.Framework.CategoryAttribute("BalanceEnquiry")]
        public async global::System.Threading.Tasks.Task SuccessfulCustomerBalanceEnquiry()
        {
            string[] tagsOfScenario = new string[] {
                    "BalanceEnquiry"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful customer balance enquiry", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 152
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table18.AddRow(new string[] {
                            "transactionId",
                            "DEP000001"});
                table18.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table18.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table18.AddRow(new string[] {
                            "amount",
                            "5000"});
                table18.AddRow(new string[] {
                            "currency",
                            "KES"});
                table18.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table18.AddRow(new string[] {
                            "narration",
                            "Cash deposit via agent"});
                table18.AddRow(new string[] {
                            "referenceNumber",
                            "REFDEP001"});
#line 153
    await testRunner.WhenAsync("agent \"AGT001\" performs a cash deposit with:", ((string)(null)), table18, "When ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table19.AddRow(new string[] {
                            "transactionId",
                            "WDL000001"});
                table19.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table19.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table19.AddRow(new string[] {
                            "amount",
                            "2000"});
                table19.AddRow(new string[] {
                            "currency",
                            "KES"});
                table19.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table19.AddRow(new string[] {
                            "narration",
                            "Cash withdrawal via agent"});
                table19.AddRow(new string[] {
                            "referenceNumber",
                            "REFWDL001"});
#line 163
    await testRunner.AndAsync("agent \"AGT001\" performs a cash withdrawal with:", ((string)(null)), table19, "And ");
#line hidden
#line 173
    await testRunner.ThenAsync("the transaction id \"WDL000001\" should be successful and the transaction status sh" +
                        "ould be \"COMPLETED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table20.AddRow(new string[] {
                            "transactionId",
                            "BAL000001"});
                table20.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table20.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table20.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table20.AddRow(new string[] {
                            "referenceNumber",
                            "REFBAL001"});
#line 174
    await testRunner.WhenAsync("agent \"AGT001\" performs a balance enquiry with:", ((string)(null)), table20, "When ");
#line hidden
#line 181
    await testRunner.ThenAsync("the available account balance for \"100200300\" should be returned as 3000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Reverse a successful withdrawal transaction")]
        [global::NUnit.Framework.CategoryAttribute("Reversal")]
        public async global::System.Threading.Tasks.Task ReverseASuccessfulWithdrawalTransaction()
        {
            string[] tagsOfScenario = new string[] {
                    "Reversal"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reverse a successful withdrawal transaction", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 184
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table21.AddRow(new string[] {
                            "transactionId",
                            "DEP000001"});
                table21.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table21.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table21.AddRow(new string[] {
                            "amount",
                            "5000"});
                table21.AddRow(new string[] {
                            "currency",
                            "KES"});
                table21.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table21.AddRow(new string[] {
                            "narration",
                            "Cash deposit via agent"});
                table21.AddRow(new string[] {
                            "referenceNumber",
                            "REFDEP001"});
#line 185
    await testRunner.WhenAsync("agent \"AGT001\" performs a cash deposit with:", ((string)(null)), table21, "When ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table22.AddRow(new string[] {
                            "transactionId",
                            "WDL000001"});
                table22.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table22.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table22.AddRow(new string[] {
                            "amount",
                            "2000"});
                table22.AddRow(new string[] {
                            "currency",
                            "KES"});
                table22.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table22.AddRow(new string[] {
                            "narration",
                            "Cash withdrawal via agent"});
                table22.AddRow(new string[] {
                            "referenceNumber",
                            "REFWDL001"});
#line 195
    await testRunner.AndAsync("agent \"AGT001\" performs a cash withdrawal with:", ((string)(null)), table22, "And ");
#line hidden
#line 205
    await testRunner.ThenAsync("the transaction id \"WDL000001\" should be successful and the transaction status sh" +
                        "ould be \"COMPLETED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table23.AddRow(new string[] {
                            "transactionId",
                            "BAL000001"});
                table23.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table23.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table23.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table23.AddRow(new string[] {
                            "referenceNumber",
                            "REFBAL001"});
#line 206
    await testRunner.WhenAsync("agent \"AGT001\" performs a balance enquiry with:", ((string)(null)), table23, "When ");
#line hidden
#line 213
    await testRunner.ThenAsync("the available account balance for \"100200300\" should be returned as 3000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table24.AddRow(new string[] {
                            "reversalTransactionId",
                            "REV000001"});
                table24.AddRow(new string[] {
                            "originalTransactionId",
                            "WDL000001"});
                table24.AddRow(new string[] {
                            "reversalReason",
                            "Customer disputed withdrawal"});
                table24.AddRow(new string[] {
                            "initiatedBy",
                            "SYSTEM_ADMIN"});
                table24.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
#line 214
    await testRunner.WhenAsync("agent \"AGT001\" performs a transaction reversal with:", ((string)(null)), table24, "When ");
#line hidden
#line 221
    await testRunner.ThenAsync("the transaction id \"REV000001\" should be successful and the transaction status sh" +
                        "ould be \"COMPLETED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 222
    await testRunner.AndAsync("the transaction id \"WDL000001\" should be successful and the transaction status sh" +
                        "ould be \"REVERSED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Withdrawal should fail when agent float is insufficient")]
        [global::NUnit.Framework.CategoryAttribute("FailedWithdrawal")]
        public async global::System.Threading.Tasks.Task WithdrawalShouldFailWhenAgentFloatIsInsufficient()
        {
            string[] tagsOfScenario = new string[] {
                    "FailedWithdrawal"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Withdrawal should fail when agent float is insufficient", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 227
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table25.AddRow(new string[] {
                            "transactionId",
                            "WDL000002"});
                table25.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table25.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table25.AddRow(new string[] {
                            "amount",
                            "1000000"});
                table25.AddRow(new string[] {
                            "currency",
                            "KES"});
                table25.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table25.AddRow(new string[] {
                            "narration",
                            "Large withdrawal attempt"});
                table25.AddRow(new string[] {
                            "referenceNumber",
                            "REFWDL002"});
#line 228
    await testRunner.WhenAsync("agent \"AGT001\" performs a cash withdrawal with which fails:", ((string)(null)), table25, "When ");
#line hidden
#line 238
    await testRunner.ThenAsync("the transaction id \"WDL000002\" should fail And the transaction status should be \"" +
                        "FAILED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 239
    await testRunner.AndAsync("the response code for transaction id \"WDL000002\" should be \"InsufficientFunds\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Deposit should fail for invalid customer account")]
        [global::NUnit.Framework.CategoryAttribute("FailedDeposit")]
        public async global::System.Threading.Tasks.Task DepositShouldFailForInvalidCustomerAccount()
        {
            string[] tagsOfScenario = new string[] {
                    "FailedDeposit"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deposit should fail for invalid customer account", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 242
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table26.AddRow(new string[] {
                            "transactionId",
                            "DEP000002"});
                table26.AddRow(new string[] {
                            "customerId",
                            "CUST999"});
                table26.AddRow(new string[] {
                            "accountNumber",
                            "999999999"});
                table26.AddRow(new string[] {
                            "amount",
                            "3000"});
                table26.AddRow(new string[] {
                            "currency",
                            "KES"});
                table26.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table26.AddRow(new string[] {
                            "narration",
                            "Invalid account deposit"});
                table26.AddRow(new string[] {
                            "referenceNumber",
                            "REFDEP002"});
#line 243
    await testRunner.WhenAsync("agent \"AGT001\" performs a cash deposit with which fails:", ((string)(null)), table26, "When ");
#line hidden
#line 253
    await testRunner.ThenAsync("the transaction id \"DEP000002\" should fail And the transaction status should be \"" +
                        "FAILED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 254
    await testRunner.AndAsync("the response code for transaction id \"DEP000002\" should be \"InvalidCustomerAccoun" +
                        "t\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Duplicate transaction should be rejected")]
        [global::NUnit.Framework.CategoryAttribute("DuplicateTransaction")]
        public async global::System.Threading.Tasks.Task DuplicateTransactionShouldBeRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "DuplicateTransaction"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Duplicate transaction should be rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 257
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table27.AddRow(new string[] {
                            "transactionId",
                            "DEP000001"});
                table27.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table27.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table27.AddRow(new string[] {
                            "amount",
                            "5000"});
                table27.AddRow(new string[] {
                            "currency",
                            "KES"});
                table27.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table27.AddRow(new string[] {
                            "narration",
                            "Cash deposit via agent"});
                table27.AddRow(new string[] {
                            "referenceNumber",
                            "REFDEP001"});
#line 258
    await testRunner.WhenAsync("agent \"AGT001\" performs a cash deposit with:", ((string)(null)), table27, "When ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table28.AddRow(new string[] {
                            "transactionId",
                            "DEP000001"});
                table28.AddRow(new string[] {
                            "customerId",
                            "CUST001"});
                table28.AddRow(new string[] {
                            "accountNumber",
                            "100200300"});
                table28.AddRow(new string[] {
                            "amount",
                            "5000"});
                table28.AddRow(new string[] {
                            "currency",
                            "KES"});
                table28.AddRow(new string[] {
                            "channel",
                            "AGENCY"});
                table28.AddRow(new string[] {
                            "narration",
                            "Cash deposit via agent"});
                table28.AddRow(new string[] {
                            "referenceNumber",
                            "REFDEP001"});
#line 268
    await testRunner.WhenAsync("agent \"AGT001\" performs a cash deposit with which fails:", ((string)(null)), table28, "When ");
#line hidden
#line 278
    await testRunner.ThenAsync("the transaction id \"DEP000001\" should fail And the transaction status should be \"" +
                        "FAILED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 279
    await testRunner.AndAsync("the response code for transaction id \"DEP000001\" should be \"DuplicateTransaction\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
